#!/bin/sh

# Check JavaScript code style
RUN_ESLINT=1
RUN_FLOW=1
RUN_TEST=1
ESLINT_PATH=`command -v ./node_modules/.bin/eslint`
FLOW_PATH=`command -v ./node_modules/.bin/flow`
TEST_PATH=`command -v NODE_ENV=test ./node_modules/mocha/bin/mocha`
JSFILES=$(git diff-index --name-status --cached HEAD | grep -v ^D | egrep '.js$|.jsx$' | cut -c3-)
JSTESTFILES=($(echo ${JSFILES[*]} | sed "s/\(\b\.js\|.jsx\+\)/.test\1/g"))
TEMP= #its temporary for filter only existing tests files
for i in ${JSTESTFILES[@]}
do
    if [ -e $i ]; then
        TEMP+=$i
    fi
done
JSTESTFILES=$TEMP
$JSTESTFILES

if [ -z "$JSFILES" ]; then
    echo -e '\e[38;5;34m\e[1m'"No JavaScript file changed for this commit.\e[0m"
    RUN_ESLINT=0
    RUN_FLOW=0
elif [ -z "$ESLINT_PATH" ]; then
    echo -e '\e[38;5;196m\e[1m'"Warning: You can't check the JS coding style.\e[0m"
    echo -e '\e[38;5;196m\e[1m'"You need to download and install eslint and set ESLINT_PATH to its path.\e[0m"
    RUN_ESLINT=0
elif [ -z "$FLOW_PATH" ]; then
    echo -e '\e[38;5;196m\e[1m'"Warning: You can't check static type in JS.\e[0m"
    echo -e '\e[38;5;196m\e[1m'"You need to download and install flow and set FLOW_PATH to its path.\e[0m"
    RUN_FLOW=0
elif [ -z "$TEST_PATH" ]; then
    echo -e '\e[38;5;196m\e[1m'"Warning: You can't run tests.\e[0m"
    echo -e '\e[38;5;196m\e[1m'"You need to download and install test runner and set TEST_PATH to its path.\e[0m"
    RUN_TEST=0
fi
# Ensuring proper coding style
if [ $RUN_ESLINT -ne 0 ]; then
    echo -e '\e[38;5;4m\e[1m'"Checking JS style errors:\e[0m"
    echo -e '\e[38;5;4m\e[1m'$JSFILES"\e[0m" | tr " " "\n"
    OUT=`$ESLINT_PATH -c ./.eslintrc $JSFILES`
    CODE=$?
    if [ $CODE -ne 0 ]; then
        echo -e '\e[38;5;196m\e[1m'"JavaScript style errors found:\e[0m"
        echo "$OUT"
        echo -en '\e[38;5;196m\e[1m'"Please fix and stage the files before commiting again.\e[0m"
        exit $CODE
    else
        echo -e '\e[38;5;34m\e[1m'"No JS code style errors found.\e[0m"
    fi
fi

# Ensuring proper static types
if [ $RUN_FLOW -ne 0 ]; then
    echo -e '\e[38;5;4m\e[1m'"Checking static types in JS code:\e[0m"
    echo -e '\e[38;5;4m\e[1m'$JSFILES"\e[0m" | tr " " "\n"
    OUT=`$FLOW_PATH`
    CODE=$?
    if [ $CODE -ne 0 ]; then
        echo -e '\e[38;5;196m\e[1m'"JavaScript static types errors found:\e[0m"
        echo "$OUT"
        echo -en '\e[38;5;196m\e[1m'"Please fix and stage the files before commiting again.\e[0m"
        exit $CODE
    else
        echo -e '\e[38;5;34m\e[1m'"No JS static types errors found.\e[0m"
    fi
fi

# Ensuring proper tests
if [ $RUN_TEST -ne 0 ]; then
    echo -e '\e[38;5;4m\e[1m'"Testing edited files:\e[0m"
    echo -e '\e[38;5;4m\e[1m'$JSFILES"\e[0m" | tr " " "\n"
    echo -e '\e[38;5;4m\e[1m'$JSTESTFILES"\e[0m" | tr " " "\n"
    OUT=`$TEST_PATH $JSTESTFILES`
    CODE=$?
    if [ $CODE -ne 0 ]; then
        echo -e '\e[38;5;196m\e[1m'"JavaScript tests fails:\e[0m"
        echo "$OUT"
        echo -en '\e[38;5;196m\e[1m'"Please fix and stage the files before commiting again.\e[0m"
        exit $CODE
    else
        echo -e '\e[38;5;34m\e[1m'"No JS tests fails.\e[0m"
    fi
fi
